papaya/api/urls.py
from django.urls import path
from . import views

app_name = "api"

urlpatterns = [
    path('category-list/', views.ProductCategories.as_view(), name="category_list"),
    path('last-news/', views.LastNews.as_view(), name="last_news"),
    path('need-games/', views.GetGame.as_view(), name="need_games"),
    path('game-by-name/', views.GetGameByName.as_view(), name="game_by_name"),
    path('game-by-category/', views.GetGameByCategory.as_view(), name="game_by_category"),
]

papaya/main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name='main'),
    path('contacts/', views.contacts, name='contacts'),
    path('about/', views.about, name='about'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('register/', views.register, name='register'),
    path('manager/', views.manage, name='manager'),
]

papaya/news/urls.py
from django.urls import path
from . import views

app_name = 'news'
urlpatterns = [
    path('', views.index, name='main'),
    path('<int:News_id>/', views.detail, name='news_detail'),
    path('manage_news/', views.manage_news, name='manage_news'),
    path('create_news/', views.create_news, name='create_news'),
    path('edit_news/<int:news_id>/', views.edit_news, name='edit_news'),
    path('delete_news/<int:news_id>/', views.delete_news, name='delete_news'),
]

papaya/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns = [
    path('', views.index, name='main'),
    path('<int:Orders_id>/', views.detail, name='orders_detail'),
    path('cart/', views.cart_detail, name='cart_detail'),
    path('add_item/<int:id>', views.add_item, name='add_item'),
    path('remove_item/<int:id>', views.remove_item, name='remove_item'),
    path('order_create/', views.order_create, name='order_create'),
    path('cart_delete/', views.cart_delete, name='cart_delete'),
    path('manage_order/', views.manage_order, name='manage_order'),
    path('edit_order/<int:order_id>/', views.edit_order, name='edit_order'),
    path('delete_order/<int:order_id>/', views.delete_order, name='delete_order'),
    path('order_create/', views.order_create, name='order_create'),
]

papaya/papaya/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'), name='main'),
    path('shop/', include('shop.urls'), name='shop'),
    path('news/', include('news.urls'), name='news'),
    path('orders/', include('orders.urls'), name='orders'),
    path('api/', include('api.urls'), name='api'),
    path('roulette/', include('roulette.urls'), name='roulette'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

papaya/roulette/urls.py
from django.urls import path
from . import views

app_name = 'roulette'
urlpatterns = [
    path('', views.index, name='main'),
    path('add-ticket/<int:ticks>/', views.add_ticket, name='add_ticket'),
    path('remove-ticket/<int:ticks>/', views.remove_ticket, name='remove_ticket'),
    path('buy-tickets/<int:ticks>/', views.buy_tickets, name='buy_tickets'),
    path('prize/<int:game_id>/', views.prize, name='prize'),
]

papaya/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.index, name='main'),
    path('<int:games_id>/', views.detail, name='shop_detail'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('manage_shop/', views.manage_shop, name='manage_shop'),
    path('create_shop/', views.create_shop, name='create_shop'),
    path('edit_shop/<int:game_id>/', views.edit_shop, name='edit_shop'),
    path('delete_shop/<int:game_id>/', views.delete_shop, name='delete_shop'),
]

papaya/main/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    tickets = models.IntegerField(default=0, verbose_name="Количество лотерейных билетов")
    client_id = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return str(self.client_id)

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

papaya/main/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from django import forms


class AuthUserForm(AuthenticationForm, forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(AuthUserForm, self).__init__(*args, **kwargs)
        self.fields['username'].label = ''
        self.fields['password'].label = ''
        self.fields['username'].widget = forms.TextInput(attrs={'class': 'form-control',
                                                                'placeholder': 'Имя пользователя'})
        self.fields['password'].widget = forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Пароль'})

    class Meta:
        model = User
        fields = ['username', 'password']


class UserCreationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)
        self.fields['username'].help_text = ''
        self.fields['username'].label = ''
        self.fields['username'].widget = forms.TextInput(attrs={'class': 'form-control',
                                                                'placeholder': 'Имя пользователя'})
        self.fields['password1'].help_text = ''
        self.fields['password1'].label = ''
        self.fields['password1'].widget = forms.PasswordInput(attrs={'class': 'form-control',
                                                                     'placeholder': 'Пароль'})
        self.fields['password2'].help_text = ''
        self.fields['password2'].label = ''
        self.fields['password2'].widget = forms.PasswordInput(attrs={'class': 'form-control',
                                                                     'placeholder': 'Подтвердите пароль'})

papaya/main/views.py
from django.shortcuts import render, redirect
from .forms import *
from .forms import UserCreationForm
from django.template import loader
from django.contrib.auth import login
from django.contrib.auth.views import LogoutView, LoginView
from django.http import HttpRequest
from datetime import datetime
from news.models import News
from .models import Profile


class Login(LoginView):
    fields = ['username', 'password']
    template_name = 'main/login.html'
    form_class = AuthUserForm


def register(request):
    assert isinstance(request, HttpRequest)
    form = UserCreationForm(request.POST)
    if request.method == "POST":
        if form.is_valid():
            reg_form = form.save(commit=False)
            reg_form.is_staff = False
            reg_form.is_superuser = False
            reg_form.date_joined = datetime.now()
            reg_form.last_login = datetime.now()
            reg_form.is_active = True
            reg_form.save()
            reg_form.backend = 'django.contrib.auth.backends.ModelBackend'
            login(request, reg_form)

            prof = Profile.objects.create(client_id=request.user)
            prof.save()

            return render(request, 'main/index.html', {'form': form})
    else:
        form = UserCreationForm()
    return render(request, 'main/register.html', {'form': form})


class Logout(LogoutView):
    template_name = 'main/index.html'


def index(request):
    last_news = News.objects.order_by('-pub_date')[:3]
    context = {
        'last_news': last_news,
    }
    return render(request, 'main/index.html', context)


def contacts(request):
    return render(request, 'main/contacts.html')


def about(request):
    return render(request, 'main/about.html')


def manage(request):
    if request.user.is_staff:
        return render(request, 'main/manager.html')
    else:
        return redirect('main:main')

papaya/main/templates/main/about.html
{% extends 'main/layout.html' %}
{% load static %}
{% block title %}О нас{% endblock %}

{% block static %}
    <link rel="stylesheet" href="{% static 'main/css/about_index.css' %}">
{% endblock %}

{% block style %}
<style>

</style>
{% endblock %}

{% block content %}
<div class="razmetka">

        <picture>
        <img src="{% static 'main/img/54.png' %}" style="width:256px;">
        </picture>

    <div class="opis">
        <a>
            Papaya Games - это интернет магазин настольных игр, где вы точно найдете игру по своему вкусу. Наши продавцы помогут вам
            выбрать игру под вашу компанию, возраст играющих и желаемое время игры. Мы уверены, что настольная игра может понравиться
            каждому, только нужно уметь подобрать правильную. Здесь вы найдете игры по приятным ценам
            с быстрой доставкой. Мы радуем вас своими играми с 2022 года. Окунитесь в мир настольных игр вместе с papaya! <br>
            Работаем круглосуточно, время работы: <b>9:00-20:00</b>.
            <br> Адрес главного магазина: <b>Псковский р-н, д.Писковичи ул. Гецентова д.2 </b>
        </a>
    </div>
</div>
{% endblock %}

papaya/main/templates/main/contacts.html
{% extends 'main/layout.html' %}
{% load static %}
{% block title %}Контакты{% endblock %}

{% block static %}
    <link rel="stylesheet" href="{% static 'main/css/contacts_index.css' %}">
{% endblock %}

{% block style %}
<style>

</style>
{% endblock %}

{% block content %}
<div class="contacts">
    <div class="main">
        <a>
            <u>По всем вопросам</u></br>
            Телефон: +79602210209 </br>
            Почта: kartashov.kirill2012@yandex.ru </br>
            Телеграм: @papayagame_bot
        </a>
    </div>
    <div class="footer">
        <a
           href="https://www.google.com/maps/place/%D0%9F%D0%B8%D1%81%D0%BA%D0%BE%D0%B2%D0%B8%D1%87%D0%B8,+%D0%9F%D1%81%D0%BA%D0%BE%D0%B2%D1%81%D0%BA%D0%B0%D1%8F+%D0%BE%D0%B1%D0%BB.,+180551/@57.8617091,28.2030913,15z/data=!3m1!4b1!4m5!3m4!1s0x46c01e1c75aadd13:0x37017af113e6ff6f!8m2!3d57.8619439!4d28.2119439?hl=ru"
           target="_blank"> <i class="fa fa-map fa-spin"></i></a>
        <a href="https://vk.com/kikartashov" target="_blank">
            <i class="fab fa-vk fa-spin"></i></a>
        <a href="https://vk.me/moneysend/kikartashov" target="_blank">
            <i class="fa fa-donate fa-spin"></i></a>
        <a href="http://instagram.com/kartashov322" target="_blank">
            <i class="fab fa-instagram fa-spin"></i></a>

    </div>
</div>
{% endblock %}

papaya/main/templates/main/index.html
{% extends 'main/layout.html' %}
{% load static %}
{% block title %}Papaya главная{% endblock %}

{% block static %}
    <link rel="stylesheet" href="{% static 'main/css/main_index.css' %}">
{% endblock %}

{% block style %}
<style>
.contain {
    background: url(static/main/img/mainback.jpg) no-repeat;
}
</style>
{% endblock %}

{% block content %}
<div class="contain">

</div>
    {% if last_news %}
<div class="lastnews">
    <b>Последние новости</b>
</div>
       <div class="news">

    {% for new in last_news %}
        <div class="new">
            <a href="{% url 'news:news_detail' new.id %}"> {{ new.title }} </a>
            <a style="width: 70%" href="{{ new.get_absolute_url }}">
                <picture>
                    <img src="{{ new.picture.url }}">
                </picture>
            </a>
        </div>
    {% endfor %}
    </div>
{% else %}
    <a>Жди новостей</a>
{% endif %}

{% endblock %}

papaya/main/templates/main/layout.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.1/css/bootstrap.min.css" integrity="sha512-T584yQ/tdRR5QwOpfvDfVQUidzfgc2339Lc8uBDtcp/wYu80d7jwBgAxbyMh0a9YM9F8N3tdErpFI8iaGx6x5g==" crossorigin="anonymous" referrerpolicy="no-referrer">
    <link rel="stylesheet" href="{% static 'main/css/site.css' %}">
    {% block static %}
    {% endblock %}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.1/js/bootstrap.min.js" integrity="sha512-UR25UO94eTnCVwjbXozyeVd6ZqpaAE9naiEUBK/A+QDbfSTQFhPGj5lOR6d8tsgbBk84Ggb5A3EkjsOgPRPcKA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'main/papaya.ico' %}">

    {% block style %}
    {% endblock %}
</head>

<body>
    <div class="fixed">
        <div class="header">
            <a href="/" style="margin: 0 1% 0 1%;"><img src="{% static 'main/img/logosite.png' %}" alt="logo" style="width: 60px; height: 60px"> </a>
            <div class="middle">
                <div class="header_left">
                    <a type="button" href="{% url 'news:main' %}" style="font-size: 22px; color: black;">Новости</a>
                    <a type="button" href="{% url 'shop:main' %}" style="font-size: 22px; color: black;">Магазин</a>
                    <a type="button" href="{% url 'roulette:main' %}?tickets=1" style="font-size: 22px; color: black;"> Рулетка</a>
                    <a type="button" href="{% url 'main:contacts' %}" style="font-size: 22px; color: black;">Контакты</a>
                    <a type="button" href="{% url 'main:about' %}" style="font-size: 22px; color: black;">О нас</a>
                    {% if user.is_staff %}
                         <a type="button" href="{% url 'main:manager' %}" style="font-size: 22px; color: black;">Панель менеджера</a>
                    {% endif %}
                </div>
                <div class="header_right">
                    {% if not user.is_authenticated %}
                        <a type="button" href="{% url 'main:register' %}" style="font-size: 22px; color: black;">Регистрация</a>
                        <a type="button" href="{% url 'main:login' %}" style="font-size: 22px; color: black;">Вход</a>
                    {% else %}
                        <a style="font-size: 22px; color: black;"> Привет, {{ user.username }}!</a>
                        <a type="button" href="{% url 'orders:cart_detail' %}" style="font-size: 22px; color: black;">Корзина</a>
                        <a type="button" href="{% url 'orders:main' %}" style="font-size: 22px; color: black;">Заказы</a>
                        <a type="button" href="{% url 'main:logout' %}" style="font-size: 22px; color: black;">Выход</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    {% block content %}
    {% endblock %}
</body>

</html>

papaya/main/templates/main/login.html
{% extends 'main/layout.html' %}
{% load static %}
{% block title %}Вход{% endblock %}

{% block static %}
    <link rel="stylesheet" href="{% static 'main/css/main_login.css' %}">
{% endblock %}

{% block style %}
    <style>

    </style>
{% endblock %}

{% block content %}

    <div class="razmetka" style="color: #4cb2ede3"><strong>Войти в аккаунт</strong></div>
    <div class="div_form">
        <div class="form">
            <form method="POST" >
                {% csrf_token %}
                {{ form.as_p }}
                <div class="btn_login">
                    <button type="submit" class="btn btn-outline-info" style="margin-left: 40%;" > Войти </button>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

papaya/main/templates/main/manager.html
{% extends "main/layout.html" %}
{% load static %}
{% block title %}
{% endblock %}

{% block static %}
    <link rel="stylesheet" href="{% static 'main/css/manager.css' %}">
{% endblock %}

{% block style %}
<style>

</style>
{% endblock %}

{% block content %}

{% if user.is_staff %}
<div class="manage">
    <h4 style="margin-left: 25px;">Страница менеджера</h4>
    <a type="button" class="btn btn-outline-info" href="{% url 'news:manage_news' %}">Управление новостями</a>
    <a type="button" class="btn btn-outline-warning" href="{% url 'shop:manage_shop' %}">Управление товарами</a>
    <a type="button" class="btn btn-outline-secondary" href="{% url 'orders:manage_order' %}">Управление заказами</a>
</div>
{% endif %}

{% endblock %}

papaya/main/templates/main/register.html
{% extends 'main/layout.html' %}
{% load static %}
{% block title %}
    Регистрация
{% endblock %}

{% block static %}
    <link rel="stylesheet" href="{% static 'main/css/main_register.css' %}">
{% endblock %}

{% block style %}
    <style>

    </style>
{% endblock %}

{% block content %}

    <a class="razmetka" style="color: #4cb2ede3"><strong>Регистрация</strong></a>
    <div class="div_form">
        <form method="POST" >
    <div class="form">
{% csrf_token %}
{{ form.as_p }}
    </div>
        <button type="submit" class="btn btn-outline-info" style="margin-left: 20%;" > Зарегистрироваться </button>
    </form>
    </div>

{% endblock %}