papaya/api/urls.py
from django.urls import path
from . import views

app_name = "api"

urlpatterns = [
    path('category-list/', views.ProductCategories.as_view(), name="category_list"),
    path('last-news/', views.LastNews.as_view(), name="last_news"),
    path('need-games/', views.GetGame.as_view(), name="need_games"),
    path('game-by-name/', views.GetGameByName.as_view(), name="game_by_name"),
    path('game-by-category/', views.GetGameByCategory.as_view(), name="game_by_category"),
]

papaya/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns = [
    path('', views.index, name='main'),
    path('<int:Orders_id>/', views.detail, name='orders_detail'),
    path('cart/', views.cart_detail, name='cart_detail'),
    path('add_item/<int:id>', views.add_item, name='add_item'),
    path('remove_item/<int:id>', views.remove_item, name='remove_item'),
    path('order_create/', views.order_create, name='order_create'),
    path('cart_delete/', views.cart_delete, name='cart_delete'),
    path('manage_order/', views.manage_order, name='manage_order'),
    path('edit_order/<int:order_id>/', views.edit_order, name='edit_order'),
    path('delete_order/<int:order_id>/', views.delete_order, name='delete_order'),
    path('order_create/', views.order_create, name='order_create'),
]

papaya/papaya/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'), name='main'),
    path('shop/', include('shop.urls'), name='shop'),
    path('news/', include('news.urls'), name='news'),
    path('orders/', include('orders.urls'), name='orders'),
    path('api/', include('api.urls'), name='api'),
    path('roulette/', include('roulette.urls'), name='roulette'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

papaya/orders/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import *
from shop.models import Games


class DeliveryPoint(models.Model):
    name = models.CharField(max_length=255)
    address = models.TextField()
    work_hours = models.CharField(max_length=50)

    def __str__(self):
        return str(self.name)

    class Meta:
        db_table = 'delivery_point'
        verbose_name = 'Пункт выдачи'
        verbose_name_plural = 'Пункты выдачи'


class PaymentType(models.Model):
    type = models.CharField(max_length=255)

    def __str__(self):
        return str(self.type)

    class Meta:
        db_table = 'payment_type'
        verbose_name = 'Способ оплаты'
        verbose_name_plural = 'Способы оплаты'


class Orders(models.Model):
    is_cart = models.BooleanField(default=True)
    total = models.IntegerField(null=True, default=0)
    client = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    phone = models.CharField(max_length=50, default='88002200220')
    delivery_address = models.ForeignKey(DeliveryPoint, on_delete=models.CASCADE, null=True)
    payment_type = models.ForeignKey(PaymentType, on_delete=models.CASCADE, null=True)
    order_date = models.CharField(max_length=50, default='25-06-2023')

    def get_absolute_url(self):
        return f'/orders/{self.id}/'

    def __str__(self):
        return str('Заказ № ' + str(self.id))

    class Meta:
        db_table = 'orders'
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'


class OrderProducts(models.Model):
    games_id = models.ForeignKey(Games, on_delete=models.CASCADE)
    order_id = models.ForeignKey(Orders, on_delete=models.CASCADE)
    amount = models.IntegerField(default=0)
    discount = models.IntegerField(default=0)

    def __str__(self):
        return str(str(self.order_id) + ', Игра: ' + str(self.games_id))

    def get_discount_price(self):
        price = Games.objects.get(title=self.games_id).price
        discount_price = int(price * (100 - self.discount) / 100)
        return discount_price

    class Meta:
        db_table = 'order_products'
        verbose_name = 'Игра в заказе'
        verbose_name_plural = 'Игры в заказе'

papaya/orders/forms.py
from django import forms
from django.forms import ModelForm
from .models import Orders, PaymentType, DeliveryPoint


class OrderForm(ModelForm):

    class Meta:
        model = Orders
        fields = ['total', 'delivery_address', 'phone', 'order_date']

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)


class OrderCreate(ModelForm):
    delivery_address = forms.ModelChoiceField(
        queryset=DeliveryPoint.objects.all()
    )
    payment_type = forms.ModelChoiceField(
        queryset=PaymentType.objects.all()
    )

    class Meta:
        model = Orders
        fields = ['delivery_address', 'phone', 'payment_type']

    def __init__(self, *args, **kwargs):
        super(OrderCreate, self).__init__(*args, **kwargs)

papaya/orders/views.py
from django.shortcuts import render, redirect
from .models import Orders, OrderProducts, DeliveryPoint
from shop.models import Games
from orders.forms import OrderForm, OrderCreate
from datetime import date, datetime, timedelta


def index(request):
    if request.user.is_active:
        orders = Orders.objects.filter(is_cart=False, client=request.user).order_by("-total")
        context = {
            "orders": orders,
        }
        return render(request, "orders/index.html", context)
    else:
        return redirect("main:main")


def detail(request, Orders_id):
    if request.user.is_active:
        try:
            if request.user.is_staff:
                ord = Orders.objects.get(pk=Orders_id)
            else:
                ord = Orders.objects.get(pk=Orders_id, client=request.user)
            delivery_point = DeliveryPoint.objects.get(name=ord.delivery_address)
            order_products = OrderProducts.objects.filter(order_id=ord)
            games = Games.objects.all()
            context = {
                "ord": ord,
                "delivery_point": delivery_point,
                "order_products": order_products,
                "games": games,
            }
            return render(request, "orders/orders_detail.html", context)
        except:
            return redirect("main:main")
    else:
        return redirect("main:main")


def cart_detail(request):
    if request.user.is_active:
        try:
            cart = Orders.objects.get(client=request.user, is_cart=True)
        except:
            cart = Orders.objects.create(client=request.user)
        order_prods = OrderProducts.objects.filter(order_id=cart.id)
        for prod in order_prods:
            print(prod.get_discount_price())
        games = Games.objects.all()
        context = {
            "cart": cart,
            "order_prods": order_prods,
            "games": games,
        }
        return render(request, "orders/cart_detail.html", context)
    else:
        return redirect("main:main")


def add_item(request, id):
    if request.user.is_active:
        game = OrderProducts.objects.get(id=id)
        game.amount += 1
        game.save()
        cart = Orders.objects.get(client=request.user, is_cart=True)
        cart.total += Games.objects.get(title=game.games_id).get_discount_price()
        cart.save()
        return redirect("orders:cart_detail")
    else:
        return redirect("main:main")


def remove_item(request, id):
    if request.user.is_active:
        game = OrderProducts.objects.get(id=id)
        game.amount -= 1
        game.save()
        cart = Orders.objects.get(client=request.user, is_cart=True)
        cart.total -= Games.objects.get(title=game.games_id).get_discount_price()
        cart.save()
        if game.amount < 1:
            game.delete()
        return redirect("orders:cart_detail")
    else:
        return redirect("main:main")


def order_create(request):
    if request.user.is_active:
        if request.method == "POST":
            form = OrderCreate(request.POST)
            if form.is_valid():
                order = Orders.objects.get(client=request.user, is_cart=True)
                today = date.today()
                today = str(today)
                dt = datetime.strptime(today, '%Y-%m-%d')
                order_date = str(dt + timedelta(days=10))
                order.order_date = order_date[:10]
                order.is_cart = False
                order.save()
                return render(request, "orders/cart_detail.html", {"form": form})
        form = OrderCreate()
        return render(request, "orders/create_order.html", {"form": form})
    else:
        return redirect("main:main")


def cart_delete(request):
    if request.user.is_active:
        cart = Orders.objects.get(client=request.user, is_cart=True)
        prods = OrderProducts.objects.filter(order_id=cart)
        cart.total = 0
        for prod in prods:
            prod.delete()
        cart.save()
        return redirect("orders:cart_detail")
    else:
        return redirect("main:main")


def manage_order(request):
    if request.user.is_staff:
        orders = Orders.objects.all()
        context = {
            "orders": orders,
        }
        return render(request, "orders/manage_order.html", context)
    else:
        return redirect("main:main")


def edit_order(request, order_id):
    if request.user.is_staff:
        order_item = Orders.objects.get(pk=order_id)
        if request.method == "POST":
            form = OrderForm(request.POST, request.FILES, instance=order_item)
            if form.is_valid():
                game_form = form.save(commit=False)
                game_form.save()
                return redirect("orders:manage_order")
        else:
            form = OrderForm(instance=order_item)
        return render(request, "orders/edit_order.html", {"form": form})
    else:
        return redirect("main:main")


def delete_order(request, order_id):
    if request.user.is_staff:
        order_item = Orders.objects.get(pk=order_id)
        order_item.delete()
        return redirect("orders:manage_order")
    else:
        return redirect("main:main")

papaya/orders/templates/orders/cart_detail.html
{% extends 'main/layout.html' %}
{% load static %}
{% block title %}Корзина{% endblock %}

{% block static %}
    <link rel="stylesheet" href="{% static 'main/css/cart_detail.css' %}">
{% endblock %}

{% block style %}
<style>

</style>
{% endblock %}

{% block content %}
<div class="title">
        <a><b>Корзина</b></a>
    </div>
<div class="orders">
    {% if order_prods %}
    <div class="containers">
            {% for prod in order_prods %}
                <div class="razmetka">
                    <div class="t_id">
                        <a>{{ prod.games_id }} </a>
                        <div class="pricing">
                            {% for game in games %}
                                {% if game == prod.games_id %}
                                    <a> <img src="{{ game.picture.url }}" style="width: 100px;"></a>
                                    <a>{{ prod.get_discount_price }} ₽ x {{ prod.amount }}</a>
                                    {% if prod.get_discount_price != 0 %}
                                    <div class="buttons"><form method="POST">
                                            <a methods="POST" type="button" class="btn btn-outline-nfo"
                                               href="{% url 'orders:add_item' prod.id %}">
                                                <i class="fa fa-plus"></i></a></form>
                                        <form method="POST">
                                            <a methods="POST" type="button" class="btn btn-outline-nfo"
                                               href="{% url 'orders:remove_item' prod.id %}">
                                                <i class="fa fa-minus"></i></a></form>
                                    </div>
                                    {% endif %}
                                    <a>{% widthratio prod.get_discount_price 1 prod.amount %} ₽ </a>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                </div>
            <div><hr></div>
            {% endfor %}
        </div>
        <div class="endprice">
            <a><b>Общая цена:</b></a>
            <a>{{ cart.total }} ₽ </a>
        </div>
    </div>
    <div class="button">
        <a type="button" class="btn btn-outline-success"  href="{% url 'orders:order_create' %}">Оплатить</a>
        <a type="button" class="btn btn-outline-danger"  href="{% url 'orders:cart_delete' %}">
            <i class="fa fa-trash"></i>Очистить корзину</a>
    </div>
    {% else %}
        <a style="font-size: 20px; margin-left: 15px;">Выберите игру, чтобы корзина не была такой пустой :с</a>
    {% endif %}
</div>
{% endblock %}

papaya/orders/templates/orders/create_order.html
{% extends "main/layout.html" %}
{% load static %}
{% block title %}
{% endblock %}

{% block static %}
    <link rel="stylesheet" href="{% static 'main/css/main_login.css' %}">
{% endblock %}

{% block style %}
<style>

</style>
{% endblock %}

{% block content %}

<a class="razmetka" style="color:black"><strong>Оформление заказа</strong></a>
<div class="div_form">
    <div class="form">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-info" style="margin-left: 42%;" > Заказать </button>
        </form>
    </div>
</div>
{% endblock %}

papaya/orders/templates/orders/edit_order.html
{% extends "main/layout.html" %}
{% load static %}
{% block title %}
{% endblock %}

{% block static %}
    <link rel="stylesheet" href="{% static 'main/css/main_login.css' %}">
{% endblock %}

{% block style %}
<style>

</style>
{% endblock %}

{% block content %}

<a class="razmetka" style="color:black"><strong>Редактирование заказа</strong></a>
<div class="div_form">
    <div class="form">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-info" style="margin-left: 42%;" > Обновить </button>
        </form>
    </div>
</div>
{% endblock %}

papaya/orders/templates/orders/index.html
{% extends 'main/layout.html' %}
{% load static %}
{% block title %}Заказы{% endblock %}

{% block static %}
    <link rel="stylesheet" href="{% static 'main/css/orders_index.css' %}">
{% endblock %}

{% block style %}
<style>

</style>
{% endblock %}

{% block content %}
<h4 style="margin: 1% 0 0 3%;">Ваши заказы</h4>
<div class="orders">
    {% if orders %}
        {% for order in orders %}
            <div class="zaka">
                <a href="{% url 'orders:orders_detail' order.id %}">{{ order }}</a>
                <a> на сумму: {{ order.total }} ₽</a>
                <a>Доставка: <br>{{ order.order_date }}</a>
            </div>
        {% endfor %}
    {% else %}
        <a>Заказов нет</a>
    {% endif %}
</div>
{% endblock %}

papaya/orders/templates/orders/manage_order.html
{% extends "main/layout.html" %}
{% load static %}
{% block title %}{% endblock %}

{% block static %}
    <link rel="stylesheet" href="{% static 'main/css/manage_order.css' %}">
{% endblock %}

{% block style %}
<style>

</style>
{% endblock %}

{% block content %}
{% for order in orders %}
<div class="edit">
    <a style="margin: 0 0 0 2%;" href="{{ order.get_absolute_url }}"> {{ order }}</a>
    <a style="margin: 0 0 0 2%;" class="btn btn-warning" href="{% url 'orders:edit_order' order.id %}"><i class="fa fa-pen"></i></a>
    <a style="margin: 0 0 0 2%;" class="btn btn-danger" href="{% url 'orders:delete_order' order.id %}"><i class="fa fa-trash"></i></a>
</div>
{% endfor %}
{% endblock %}

papaya/orders/templates/orders/orders_detail.html
{% extends 'main/layout.html' %}
{% load static %}
{% block title %}{{ ord }}{% endblock %}

{% block static %}
<link rel="stylesheet" href="{% static 'main/css/orders_detail.css' %}">
{% endblock %}

{% block style %}
<style>

</style>
{% endblock %}

{% block content %}
<div class="orders_block">
    <div class="title">
        <b>{{ ord }}</b>
    </div>
    <div class="space">
        {% for prod in order_products %}
        {% for game in games %}
        {% if game == prod.games_id %}
            <div class="info_block">
                    {{ game.title }}
                <picture>
                    <img src="{{ game.picture.url }}">
                </picture>
                    <a>Кол-во:{{ prod.amount }}</a>
                    <a>Стоимость: {% widthratio game.price 1 prod.amount %} ₽ </a>
            </div>
            <div class="content_block">

            </div>
        {% endif %}
        {% endfor %}
        {% endfor %}
    </div>
    <div class="endprice">
        <a><u>Цена заказа:</u> <b>{{ ord.total }} ₽ </b> </a>
        <a>Пункт выдачи: {{delivery_point.address}}</a>
        <a>Время работы пункта: {{ delivery_point.work_hours }} </a>
        <a>Дата доставки: {{ord.order_date}}</a>
        <a>Способ оплаты: {{ord.payment_type}}</a>
        {% if user.is_staff %}
            <a>Имя клиента: {{ord.client}}</a>
            <a>Телефон для связи: {{ord.phone}}</a>
        {% endif %}
    </div>
</div>
{% endblock %}