papaya/api/urls.py
from django.urls import path
from . import views

app_name = "api"

urlpatterns = [
    path('category-list/', views.ProductCategories.as_view(), name="category_list"),
    path('last-news/', views.LastNews.as_view(), name="last_news"),
    path('need-games/', views.GetGame.as_view(), name="need_games"),
    path('game-by-name/', views.GetGameByName.as_view(), name="game_by_name"),
    path('game-by-category/', views.GetGameByCategory.as_view(), name="game_by_category"),
]

papaya/papaya/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'), name='main'),
    path('shop/', include('shop.urls'), name='shop'),
    path('news/', include('news.urls'), name='news'),
    path('orders/', include('orders.urls'), name='orders'),
    path('api/', include('api.urls'), name='api'),
    path('roulette/', include('roulette.urls'), name='roulette'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

papaya/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.index, name='main'),
    path('<int:games_id>/', views.detail, name='shop_detail'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('manage_shop/', views.manage_shop, name='manage_shop'),
    path('create_shop/', views.create_shop, name='create_shop'),
    path('edit_shop/<int:game_id>/', views.edit_shop, name='edit_shop'),
    path('delete_shop/<int:game_id>/', views.delete_shop, name='delete_shop'),
]

papaya/shop/models.py
import random
import string
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.contrib.auth.models import User
from datetime import *


class Category(models.Model):
    category = models.CharField(max_length=60)
    description = models.TextField(default='Эта категория вам понравится', verbose_name='Описание категории')

    def __str__(self):
        return self.category

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Games(models.Model):
    title = models.CharField(null=False, blank=False, max_length=100, verbose_name='Название игры')
    games = models.TextField(verbose_name='Описание игры')
    picture = models.ImageField(upload_to='images/')
    category_class = models.ForeignKey(Category, on_delete=models.CASCADE, default=1, verbose_name='Категория товара')
    price = models.FloatField(default=1000, verbose_name='Цена')
    components = models.TextField(default='Отсутствуют', verbose_name='Компоненты')
    min_players = models.IntegerField(default=1, verbose_name='Минимальное количество игроков')
    max_players = models.IntegerField(default=2, verbose_name='Максимальное количество игроков')
    recommend_age = models.IntegerField(default=4, verbose_name='Рекомендуемый возраст')
    game_time = models.IntegerField(default=40, verbose_name='Среднее время игры')
    vendor = models.TextField(default='PapayaGames', verbose_name='Производитель')
    discount = models.IntegerField(default=0, verbose_name='Скидка на товар')
    is_active = models.BooleanField(default=True, verbose_name='Существует')

    class Meta:
        verbose_name = 'Игра'
        verbose_name_plural = 'Игры'
        db_table = "games"

    def get_absolute_url(self):
        return f'/shop/{self.id}/'

    def get_discount_price(self):
        discount_price = int(self.price * (100 - self.discount) / 100)
        return discount_price

    def __str__(self):
        return self.title


class Comment(models.Model):
    author = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL,
                               verbose_name='Автор комментария')
    game = models.ForeignKey(Games, blank=True, null=True, on_delete=models.SET_NULL)
    text = models.CharField(null=False, blank=False, max_length=500, verbose_name='Комментарий')
    pub_date = models.DateTimeField(default=datetime.now)
    rating = models.IntegerField(default=5, null=False, validators=[MinValueValidator(1), MaxValueValidator(5)])

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

papaya/shop/forms.py
from django import forms
from django.forms import ModelForm
from .models import Games, Comment


class ShopForm(ModelForm):

    class Meta:
        model = Games
        fields = ['title', 'games', 'picture', 'category_class', 'price']

    def __init__(self, *args, **kwargs):
        super(ShopForm, self).__init__(*args, **kwargs)


class CommentForm(ModelForm):

    class Meta:
        model = Comment
        fields = ['text', 'rating']

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['text'].help_text = 'Здесь пишут отзыв'
        self.fields['text'].label = ''
        self.fields['text'].widget = forms.TextInput(attrs={
            'placeholder': 'Опишите ваши впечатления от покупки',
            'class': 'form-control',
        })

papaya/shop/views.py
from datetime import *

from django.shortcuts import redirect, render, get_object_or_404

from orders.models import OrderProducts, Orders

from .forms import CommentForm, ShopForm
from .models import Category, Comment, Games


def index(request):
    categories = Category.objects.all().order_by("-category")
    sort = str(request.GET.get("name"))
    filtrate_by = str(request.GET.get("filtrate_by"))
    boolka = 0
    if sort != "None":
        title = Category.objects.get(id=int(sort)).category
        if filtrate_by == "price_up":
            games = Games.objects.filter(
                category_class=int(sort), is_active=True
            ).order_by("price")
        elif filtrate_by == "price_down":
            games = Games.objects.filter(
                category_class=int(sort), is_active=True
            ).order_by("-price")
        else:
            games = Games.objects.filter(
                category_class=int(sort), is_active=True
            ).order_by("title")
        boolka = 1
        
    else:
        if filtrate_by == "price_up":
            games = Games.objects.all().order_by("price")
        elif filtrate_by == "price_down":
            games = Games.objects.all().order_by("-price")
        else:
            games = Games.objects.all().order_by("title")
        title = "Все товары"
    context = {
        "flag": sort,
        "boolka": boolka,
        "games": games,
        "categories": categories,
        "title": title,
    }
    return render(request, "shop/index.html", context)


def detail(request, games_id):
    game = Games.objects.get(pk=games_id)
    comments = Comment.objects.all()
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            com_fom = form.save(commit=False)
            com_fom.author = request.user
            com_fom.game = game
            com_fom.pub_date = datetime.now()
            com_fom.save()
            form = CommentForm()
            context = {
                "game": game,
                "form": form,
                "comments": comments,
            }
            return render(request, "shop/shop_detail.html", context)
    form = CommentForm()

    context = {
        "game": game,
        "form": form,
        "comments": comments,
    }
    return render(request, "shop/shop_detail.html", context)


def add_to_cart(request, product_id):
    if request.user.is_active:
        game = Games.objects.get(id=product_id)

        try:
            cart = Orders.objects.get(client=request.user, is_cart=True)
        except:
            cart = Orders.objects.create(client=request.user)

        try:
            check = OrderProducts.objects.get(games_id=game, order_id=cart)
            if check.discount == 100:
                return redirect("orders:cart_detail")
            check.amount += 1
            check.discount = game.discount
            check.save()
            cart.total += check.get_discount_price()
            cart.save()
        except:
            prod = OrderProducts()
            prod.games_id = game
            prod.order_id = cart
            prod.amount = 1
            prod.discount = game.discount
            prod.save()
            cart.total += prod.get_discount_price()
            cart.save()
        return redirect("orders:cart_detail")
    else:
        return redirect("main:main")


def manage_shop(request):
    if request.user.is_staff:
        games = Games.objects.all()
        context = {
            "games": games,
        }
        return render(request, "shop/manage_shop.html", context)
    else:
        return redirect("main:main")


def create_shop(request):
    if request.user.is_staff:
        if request.method == "POST":
            form = ShopForm(request.POST, request.FILES)
            if form.is_valid():
                game_form = form.save(commit=False)
                game_form.save()
                return redirect("shop:manage_shop")
        else:
            form = ShopForm()
        return render(request, "shop/create_shop.html", {"form": form})
    else:
        return redirect("main:main")


def edit_shop(request, game_id):
    if request.user.is_staff:
        game_item = Games.objects.get(pk=game_id)
        if request.method == "POST":
            form = ShopForm(request.POST, request.FILES, instance=game_item)
            if form.is_valid():
                game_form = form.save(commit=False)
                game_form.save()
                return redirect("shop:manage_shop")
        else:
            form = ShopForm(instance=game_item)
        return render(request, "shop/edit_shop.html", {"form": form})
    else:
        return redirect("main:main")


def delete_shop(request, game_id):
    if request.user.is_staff:
        game_item = Games.objects.get(pk=game_id)
        game_item.delete()
        return redirect("shop:manage_shop")
    else:
        return redirect("main:main")

papaya/shop/templates/shop/create_shop.html
{% extends "main/layout.html" %}
{% load static %}
{% block title %}
{% endblock %}

{% block static %}
    <link rel="stylesheet" href="{% static 'main/css/main_login.css' %}">
{% endblock %}

{% block style %}
<style>

</style>
{% endblock %}

{% block content %}

<a class="razmetka" style="color:black"><strong>Добавление товара</strong></a>
<div class="div_form">
    <div class="form">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-info" style="margin-left: 42%;" > Создать </button>
        </form>
    </div>
</div>
{% endblock %}

papaya/shop/templates/shop/edit_shop.html
{% extends "main/layout.html" %}
{% load static %}
{% block title %}
{% endblock %}

{% block static %}
    <link rel="stylesheet" href="{% static 'main/css/main_login.css' %}">
{% endblock %}

{% block style %}
<style>

</style>
{% endblock %}

{% block content %}

<a class="razmetka" style="color:black"><strong>Редактирование товара</strong></a>
<div class="div_form">
    <div class="form">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-info" style="margin-left: 42%;" > Обновить </button>
        </form>
    </div>
</div>
{% endblock %}

papaya/shop/templates/shop/index.html
{% extends 'main/layout.html' %}
{% load static %}
{% block title %}Магазин{% endblock %}

{% block static %}
<link rel="stylesheet" href="{% static 'main/css/shop_index.css' %}">
{% endblock %}

{% block style %}
<style>

</style>
{% endblock %}

{% block content %}

<div class="razmetka">

    <div class="categories">
        <p style="margin:1% 0 0 1%; font-size:22px; color: #00131C ">Категории</p>
        Вы сейчас в {{ title }}
        <div class="category">
            <a href="{% url 'shop:main' %}"> Все товары </a>
        {% for category in categories %}
                <a href="{% url 'shop:main' %}?name={{ category.id }}"> {{ category.category }} </a>
        {% endfor %}
            <br> Сортировка товаров:
            {% if boolka == 1 %}
            <a class="btn btn-outline-danger"
                   href="{% url 'shop:main' %}?name={{ flag }}&filtrate_by=price_up">По возрастанию цены</a>
            <a class="btn btn-outline-danger"
                   href="{% url 'shop:main' %}?name={{ flag }}&filtrate_by=price_down">По убыванию цены</a>
            {% else %}
            <a class="btn btn-outline-primary"
                   href="{% url 'shop:main' %}?filtrate_by=price_up">По возрастанию цены</a>
            <a class="btn btn-outline-primary"
                   href="{% url 'shop:main' %}?filtrate_by=price_down">По убыванию цены</a>
            {% endif %}
            </div>
    </div>

    <div class="games">
    {% if games %}
        {% for game in games %}
            <div class="game">

                    <picture>
                        <a href="{{ game.get_absolute_url }}">
                            <img src="{{ game.picture.url }}"></br>
                        </a>
                    </picture>
                <div class="title">
                <a href="{% url 'shop:shop_detail' game.id %}"> {{ game.title }} </a> </br>
                    {% if game.discount > 0 %}
                    <a><strike>{{game.price}}₽</strike> {{game.get_discount_price}}₽</a>
                    {% else %}
                    <a>{{game.price}}₽</a>
                    {% endif %}
                </div>
                {% if user.is_active %}
                <form method="POST">
                    <a methods="POST" type="button" class="btn btn-outline-info" href="{% url 'shop:add_to_cart' game.id %}">
                        Добавить в корзину
                        <i class="fa fa-plus"></i></a>
                </form>
                {% endif %}
            </div>
        {% endfor %}
    {% else %}
        <a>Игр пока нет</a>
    {% endif %}
    </div>

</div>
{% endblock %}

papaya/shop/templates/shop/manage_shop.html
{% extends "main/layout.html" %}
{% load static %}
{% block title %}{% endblock %}

{% block static %}
    <link rel="stylesheet" href="{% static 'main/css/manage_shop.css' %}">
{% endblock %}

{% block style %}
<style>

</style>
{% endblock %}

{% block content %}
<div class="button">
    <a>Добавить товар</a>
    <a style="margin: 0 0 0 2%;" class="btn btn-success" href="{% url 'shop:create_shop' %}"><i class="fa fa-plus"></i></a>
</div>
{% for game in games %}
<div class="edit">
    <a style="margin: 0 0 0 2%;" href="{{ game.get_absolute_url }}">{{ game.title }}</a>
    <a style="margin: 0 0 0 2%;" class="btn btn-warning" href="{% url 'shop:edit_shop' game.id %}"><i class="fa fa-pen"></i></a>
    <a style="margin: 0 0 0 2%;" class="btn btn-danger" href="{% url 'shop:delete_shop' game.id %}"><i class="fa fa-trash"></i></a>
</div>
{% endfor %}
{% endblock %}

papaya/shop/templates/shop/shop_detail.html
{% extends 'main/layout.html' %}
{% load static %}
{% block title %}{{ game.title }}{% endblock %}

{% block static %}
    <link rel="stylesheet" href="{% static 'main/css/shop_detail.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/main_login.css' %}">
{% endblock %}

{% block style %}
<style>

</style>
{% endblock %}

{% block content %}
<div class="page_content">
    <div class="product_detail">
        <div class="games_block">
            <a><b>{{game.title}}</b></a>
        </div>
            <div class="pict">
                <div class="icons">
                    {{game.recommend_age}}+ лет
                <img src="{% static 'main/img/players.png' %}" style="width: 30px; height: 30px;"> {{game.min_players}}-{{game.max_players}}
                <img src="{% static 'main/img/clock.png' %}" style="width: 30px; height: 30px;"> {{game.game_time}}
            </div>
            <picture>
                <img src="{{ game.picture.url }}">
                <div class="price">
                   {% if game.discount > 0 %}
                    <a><strike>{{game.price}}₽</strike> <b>{{game.get_discount_price}}₽</b></a>
                    {% else %}
                    <a><b>{{game.price}}₽</b></a>
                    {% endif %}
                </div>
                {% if user.is_active %}
                <div class="button">
                    <a type="button" class="btn btn-outline-info"  href="{% url 'shop:add_to_cart' game.id %}">
                        Добавить в корзину
                            <i class="fa fa-plus"></i></a>
                </div>
                {% endif %}
                <a type="button" class="btn btn-outline-success" href="{% url 'shop:main' %}" style="margin: 3% 0 0 35%;">В магазин</a>
            </picture>
        </div>
        <div class="games_block">
            <div class="text">
                <p><b>{{game.games|linebreaks}}</b></p> <br>
                <p><b>Компоненты: {{game.components|linebreaks}}</b></p> <br>
                <p>Производитель: {{game.vendor}}</p>
            </div>
        </div>
    </div>


    <div class="comments">
        <a>Комментарии:</a>
        {% if comments %}
            {% for comment in comments %}
                {% if comment in game.comment_set.all %}
                    <div class="user_comment">
                        <a><strong>{{ comment.author }}</strong> {{ comment.pub_date }} : <br> {{ comment.text }}
                        <br> Оценка товара: {{ comment.rating }}</a>
                    </div>
                {% endif %}
            {% endfor %}
        {% else %}
            <a>Оставьте комментарий первым</a>
        {% endif %}

        {% if user.is_authenticated %}
            <div class="div_form">
                <div class="form">
                    <form method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-info" style="margin-left: 23%;" > Оставить комментарий </button>
                    </form>
                </div>
            </div>
        {% else %}
            <a>Авторизуйтесь, чтобы оставить комментарий</a>
        {% endif %}
    </div>
</div>

{% endblock %}