papaya/api/urls.py
from django.urls import path
from . import views

app_name = "api"

urlpatterns = [
    path('category-list/', views.ProductCategories.as_view(), name="category_list"),
    path('last-news/', views.LastNews.as_view(), name="last_news"),
    path('need-games/', views.GetGame.as_view(), name="need_games"),
    path('game-by-name/', views.GetGameByName.as_view(), name="game_by_name"),
    path('game-by-category/', views.GetGameByCategory.as_view(), name="game_by_category"),
]

papaya/news/urls.py
from django.urls import path
from . import views

app_name = 'news'
urlpatterns = [
    path('', views.index, name='main'),
    path('<int:News_id>/', views.detail, name='news_detail'),
    path('manage_news/', views.manage_news, name='manage_news'),
    path('create_news/', views.create_news, name='create_news'),
    path('edit_news/<int:news_id>/', views.edit_news, name='edit_news'),
    path('delete_news/<int:news_id>/', views.delete_news, name='delete_news'),
]

papaya/papaya/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'), name='main'),
    path('shop/', include('shop.urls'), name='shop'),
    path('news/', include('news.urls'), name='news'),
    path('orders/', include('orders.urls'), name='orders'),
    path('api/', include('api.urls'), name='api'),
    path('roulette/', include('roulette.urls'), name='roulette'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

papaya/news/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import *


class News(models.Model):
    author = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL,
                               verbose_name='Автор публикации')
    title = models.CharField(null=False, blank=False, max_length=100, verbose_name='Заголовок')
    news = models.TextField(verbose_name='Текст')
    pub_date = models.DateTimeField(default=datetime.now)
    picture = models.ImageField(upload_to='images/')

    def get_absolute_url(self):
        return f'/news/{self.id}/'

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'

papaya/news/forms.py
from django import forms
from django.forms import ModelForm
from .models import News


class NewsForm(ModelForm):

    class Meta:
        model = News
        fields = ['title', 'news', 'picture', 'author']

    def __init__(self, *args, **kwargs):
        super(NewsForm, self).__init__(*args, **kwargs)

papaya/news/views.py
from django.shortcuts import render, redirect
from .models import News
from datetime import *
from .forms import NewsForm


def index(request):
    news = News.objects.all().order_by('-pub_date')
    context = {
        'news': news,
    }
    return render(request, 'news/index.html', context)


def detail(request, News_id):
    new = News.objects.get(pk=News_id)
    context = {
        'new': new,
    }
    return render(request, 'news/news_detail.html', context)


def manage_news(request):
    if request.user.is_staff:
        news = News.objects.all()
        context = {
            'news': news,
        }
        return render(request, 'news/manage_news.html', context)
    else:
        return redirect('main:main')


def create_news(request):
    if request.user.is_staff:
        if request.method == "POST":
            form = NewsForm(request.POST, request.FILES)
            if form.is_valid():
                news_form = form.save(commit=False)
                news_form.pub_date = datetime.now()
                news_form.save()
                return redirect('news:manage_news')
        else:
            form = NewsForm()
        return render(request, 'news/create_news.html', {'form': form})
    else:
        return redirect('main:main')


def edit_news(request, news_id):
    if request.user.is_staff:
        news_item = News.objects.get(pk=news_id)
        if request.method == "POST":
            form = NewsForm(request.POST, request.FILES, instance=news_item)
            if form.is_valid():
                news_form = form.save(commit=False)
                news_form.pub_date = datetime.now()
                news_form.save()
                return redirect('news:manage_news')
        else:
            form = NewsForm(instance=news_item)
        return render(request, 'news/edit_news.html', {'form': form})
    else:
        return redirect('main:main')


def delete_news(request, news_id):
    if request.user.is_staff:
        news_item = News.objects.get(pk=news_id)
        news_item.delete()
        return redirect('news:manage_news')
    else:
        return redirect('main:main')

papaya/news/templates/news/create_news.html
{% extends "main/layout.html" %}
{% load static %}
{% block title %}
{% endblock %}

{% block static %}
    <link rel="stylesheet" href="{% static 'main/css/main_login.css' %}">
{% endblock %}

{% block style %}
<style>

</style>
{% endblock %}

{% block content %}

<a class="razmetka" style="color:black"><strong>Создание новости</strong></a>
<div class="div_form">
    <div class="form">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-info" style="margin-left: 42%;" > Создать </button>
        </form>
    </div>
</div>
{% endblock %}

papaya/news/templates/news/edit_news.html
{% extends "main/layout.html" %}
{% load static %}
{% block title %}
{% endblock %}

{% block static %}
    <link rel="stylesheet" href="{% static 'main/css/main_login.css' %}">
{% endblock %}

{% block style %}
<style>

</style>
{% endblock %}

{% block content %}

<a class="razmetka" style="color:black"><strong>Редактирование новости</strong></a>
<div class="div_form">
    <div class="form">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-info" style="margin-left: 42%;" > Обновить </button>
        </form>
    </div>
</div>
{% endblock %}

papaya/news/templates/news/index.html
{% extends 'main/layout.html' %}
{% load static %}
{% block title %}Новости{% endblock %}

{% block static %}
    <link rel="stylesheet" href="{% static 'main/css/news_index.css' %}">
{% endblock %}

{% block style %}
<style>

</style>
{% endblock %}

{% block content %}
<div class="news">
    {% if news %}
        {% for new in news %}
            <div class="new" data-hint="Нажмите, чтобы прочитать">
                <a href="{% url 'news:news_detail' new.id %}"> {{ new.title }} </a>
                <a style="width: 90%;" href="{{ new.get_absolute_url }}">
                    <picture>
                        <img src="{{ new.picture.url }}">
                    </picture>
                </a>
            </div>
        {% endfor %}
    {% else %}
        <a>Жди новостей</a>
    {% endif %}
</div>

{% endblock %}

papaya/news/templates/news/manage_news.html
{% extends "main/layout.html" %}
{% load static %}
{% block title %}{% endblock %}

{% block static %}
    <link rel="stylesheet" href="{% static 'main/css/manage_news.css' %}">
{% endblock %}

{% block style %}
<style>

</style>
{% endblock %}

{% block content %}
<div class="button">
    <a>Добавить новость</a>
    <a style="margin: 0 0 0 2%;" class="btn btn-success" href="{% url 'news:create_news' %}"><i class="fa fa-plus"></i></a>
</div>
{% for new in news %}
<div class="edit">
    <a style="margin: 0 0 0 2%;" href="{{ new.get_absolute_url }}">{{ new.title }}</a>
    <a style="margin: 0 0 0 2%;" class="btn btn-warning" href="{% url 'news:edit_news' new.id %}"><i class="fa fa-pen"></i></a>
    <a style="margin: 0 0 0 2%;" class="btn btn-danger" href="{% url 'news:delete_news' new.id %}"><i class="fa fa-trash"></i></a>
</div>
{% endfor %}
{% endblock %}

papaya/news/templates/news/news_detail.html
{% extends 'main/layout.html' %}
{% load static %}
{% block title %}{{ new.title }}{% endblock %}

{% block static %}
    <link rel="stylesheet" href="{% static 'main/css/news_detail.css' %}">
{% endblock %}

{% block style %}
<style>

</style>
{% endblock %}

{% block content %}
<div class="news_block">
    <div class="title">
        <a><b>{{new.title}}</b></a>
    </div>
    <div class="content_block">
        <div class="pic">
            <picture>
                <img src="{{ new.picture.url }}">
            </picture>
        </div>
        <div class="info_block">
            <a>{{new.news|linebreaks}}</a>
            <div class="auth">
                <a style="align-self: flex-end;">©{{new.author}}  {{new.pub_date}}</a>
            </div>
            <a type="button" class="btn btn-outline-success" href="{% url 'news:main' %}" style="margin: 1% 0 0 5%;">Назад</a>
        </div>
    </div>
</div>
{% endblock %}